[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.args = ["-DCMAKE_CXX_STANDARD=17"]

[project]
name = "greedy_joining"
version = "0.0.1"